version: '2.1'

services:
  users_db:
    container_name: users_db
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  users_ms:
    container_name: users_ms
    image: fgomezl/register_and_auth_ms
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:3001"
    depends_on:
      - users_db
    environment:
      PORT: '3001'
    #ports:
    #  - "3001:3001"
  lists-db:
    container_name: lists_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: lists-db
      MYSQL_HOST: lists-db
  #microservicio de recursos
  lists-ms:
    container_name: lists_ms
    image: serbatero/lists-ms
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - /lists-app
    environment:
      PORT: '4000'
    #ports:
    #  - "4000:4000"
    depends_on:
      - lists-db
  songs_path_db:
    container_name: songs_path_db
    image: mongo
    ports:
      - "27017:27017"
  songs_path_ms:
    container_name: songs_path_ms
    image: pahigueraf/songs_path
    restart: always
    #ports:
    #  - "3003:3003"
    environment:
      PORT: '3003'
    links:
      - songs_path_db
  upload_song_ms:
    container_name: upload_song_ms
    image: pahigueraf/upload_songs_ms
    restart: always
    ports:
      - "3002:3002"
  tumusica-api:
    image: pahigueraf/tumusica-api
    environment:
      SHOW_URLS: 'true'
      LISTS_URL: 'lists-ms'
      LISTS_PORT: '4000'
      LISTS_ENTRY: '/'
      #WSINTERFACE_URL: '192.168.99.101'
      #WSINTERFACE_PORT: '4500'
      #WSINTERFACE_ENTRY: '/'
      #PLAY_URL: '192.168.99.101'
      #PLAY_PORT: '3004'
      #PLAY_ENTRY: '/api'
      USERS_URL: 'users-ms'
      USERS_PORT: '3001'
      USERS_ENTRY: 'api/v1'
      UPLOAD_URL: 'upload_song_ms'
      UPLOAD_PORT: '3002'
      UPLOAD_ENTRY: ''
      PATH_URL: 'songs_path_ms'
      PATH_PORT: '3003'
      PATH_ENTRY: ''
      PORT: '5000'
    #ports:
    #  - "5000:5000"
  tumusica-proxy:
    image: pahigueraf/sa_academy_proxy
    container_name: tumusica_proxy
    depends_on:
      - tumusica-api
    ports:
      - "80:80"
  play_song_ms:
    container_name: play_song_ms
    image: campuzanoa/docker_play_song_ms
    environment:
      PORT: '3004'
    ports:
      - "3004:3004"
    links:
      - songs_path_db
  tu-musica-web:
    container_name: tu-musica_wa
    image: pahigueraf/tumusica_web_client
    ports:
      - "4100:4100"  
