version: '2.1'

services:
  users_db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  users_ms:
    image: fgomezl/register_and_auth_ms
    depends_on:
      - users_db
    ports:
      - "3001:3001"
  lists-db:
    container_name: lists-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: lists-db
      MYSQL_HOST: lists-db
  #microservicio de recursos
  lists-ms:
    container_name: lists-ms
    image: serbatero/lists-ms
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - /lists-app
    ports:
      - "4000:4000"
    depends_on:
      - lists-db      

